### ISSUE TITLE
Atualizar URL repo

### ISSUE THREAD

**Issue by vasconsaurus** [vasconsaurus/ada-ci#6]
Isso aqui eu acho que eu não entendi muito bem pra que serve. @gabriela-gnsales, você quer adicionar uma descrição?

**Comment by gabriela-gnsales** [comment]
Então meninas, sugiro uma pequena alteração no arquivo Jenkinsfile, na parte da URL: colocar a URL HTTPS em vez da SSH, já que nosso repositório é público e não necessita de credencial... Vou criar uma branch e PR para fazer essa alteração, daí vocês avaliam a aprovação ou não :)
